# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
executorType: machine
jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: maven install
          command: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn test jacoco:report coveralls:report -DrepoToken=${COVERALLS_REPOTOKEN}

  release-snapshot:
    docker:
      - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Release Snapshot
          command: mvn -s ./.circleci/.circleci.settings.xml -DskipTests deploy

  release-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: maven install
          command: mvn clean install -DskipTests
      - run:
          name: Release docker image
          command: ./.scripts/build-docker-image.sh latest

  release-docker-image-snapshot:
    machine: true
    steps:
      - checkout
      - run:
          name: maven install
          command: mvn clean install -DskipTests snapshot
      - run:
          name: Release docker image
          command: ./.scripts/build-docker-image.sh

  release:
    docker:
      - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Release
          command: ./.scripts/handle-maven-release.sh

  update-dev-branch:
    docker:
      - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Update dev branch
          command: ./.scripts/update-development-branch-version.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - release-snapshot:
          requires:
            - build-and-test
          filters:
            branches:
              only: development
      - release-docker-image-snapshot:
          requires:
            - build-and-test
          filters:
            branches:
              only: development
      - release:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - release-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - update-dev-branch:
          requires:
            - release
          filters:
            branches:
              only: master
